BaseURL = "http://reyoung.me/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "于洋的闲七杂吧"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "reyoung"

[Params]
  AuthorHomepage = "http://reyoung.me"
  BottomIntroduce = "于洋 <br/> <span style='font-size: 12px;'>08年在天津大学读本科，15年硕士毕业。现在在百度IDL写机器学习系统。</span>"
  Description = ""
  Subtitle = "reyoung's blog"
  Weibo = "tjureyoung"
  WeiboID = 2154941244
  GitHub = "reyoung"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  [Params.DuoShuo]
    ShortName = "reyoung"

  [Params.GoogleAnalytics]
    ID = "UA-77097213-1"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "博客"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2